---
title: "Examples"
---

This section will contain annotated **R** code along with worked out examples. If time permits, I will also include videos of me life-coding, so you can see me making programming mistakes in real time!

Useful resources for learning **R**, the `tidyverse` and Rmarkdown basics include

- The [Introduction to **R** and RStudio](http://openintrostat.github.io/oilabs-tidy/01_intro_to_r/intro_to_r.html) by Open Intro Stat
- [Teacups, giraffes & statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html): basic statistical concepts and programming
- the notebook [**RYouWithMe** from R-Ladies Sydney](https://rladiessydney.org/courses/ryouwithme/)
- the book [**R** for Data Science](https://r4ds.had.co.nz/index.html), which adheres to the `tidyverse` principles.
- the **R** package [DoSStoolkit](https://dosstoolkit.com/), developped at the University of Toronto.
- the [`introverse`](https://sjspielman.github.io/introverse/) documentation.
- the [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/), also available from RStudio menu in Help > Cheat Sheets
- Norman Matloff's [*Fast Lane to Learning R!*](https://github.com/matloff/fasteR)

To install all **R** packages used throughout the course, use the command
```{r, eval=FALSE, echo=TRUE}
libs <- c("afex", "car", "dplyr", "emmeans", "effectsize", 
         "ggplot2", "lme4", "lmerTest", "mediation", "nlme", 
         "patchwork", "pwr", "remotes", "tidyr", "WebPower")
for(lib in libs){
  if(!lib %in% installed.packages()[,"Package"]){
   install.packages(lib)
  }
}
# Load package containing databases
remotes::install_github("lbelzile/hecedsm")

```
