---
title: "Two-way analysis of variance"
linktitle: "Two-way ANOVA"
type: docs
editor_options: 
  chunk_output_type: console
---



We consider data from a replication by Chandler (2016) of Study 4a of Janiszewski and Uy (2008). Both studies measured the amount of adjustment when presented with vague or precise range of value for objects, with potential encouragement for adjusting more the value.

@Chandler:2016 described the effect in the replication report:

> Janiszewski and Uy (2008) conceptualized people’s attempt to adjust following presentation of an anchor as movement along a subjective representation scale by a certain number of units. Precise numbers (e.g. $9.99) imply a finer-resolution scale than round numbers (e.g. $10). Consequently, adjustment along a subjectively finer resolution scale will result in less objective adjustment than adjustment by the same number of units along a subjectively coarse resolution scale.

The experiment is a 2 by 2 factorial design (two-way ANOVA) with `anchor` (either round or precise) and `magnitude` (`0` for small, `1` for big adjustment) as experimental factors. A total of 120 students were recruited and randomly assigned to one of the four experimental sub-condition, for a total of 30 observations per subgroup (`anchor`, `magnitude`). The response variable is `majust`, the mean adjustment for the price estimate of the item.

```{r}
#| eval: true
#| echo: false
# Example of two-way ANOVA with balanced design
data(C16, package = "hecedsm")
# Check for balance
xtabs(formula = ~ anchor + magnitude,
      data = C16)
# Fit two-way ANOVA model
mod <- aov(madjust ~ anchor * magnitude,
           data = C16)
# Interaction plot
with(C16,
  interaction.plot(
    x.factor = anchor,
    trace.factor = magnitude,
    response = madjust)
)
# Lines pretty parallel, no interaction

# Get mu, alpha, beta, alpha.beta coefs
dummy.coef(mod)
model.tables(mod, type = "means")


## Check model assumptions
# Evidence of unequal variance (multiplicative?)
plot(resid(mod)~ fitted(mod))
car::leveneTest(mod) #Brown-Forsythe
# Normality - sample size okay-ish
car::qqPlot(mod, id = FALSE)


# Analysis of variance table
anova(mod)
# No evidence of interaction
# Proceed with main effects

# Estimated marginal means per cell
emm <- emmeans::emmeans(
  object = mod,
  specs = c("anchor", "magnitude"),
)
# specs: what variables to keep?

# Marginal effect for anchor
# Warning about interaction
emm_marg <- emmeans::emmeans(
  object = mod,
  specs = "anchor"
)
# Simple effects for anchor
emm_simple <- emmeans::emmeans(
  object = mod,
  specs = "anchor",
  by = "magnitude"
)
# Compute pairwise differences within each magnitude
pairs(emm_simple)
```


## References
