---
title: "Problem set 4"
---

I encourage you to work in teams for this problem set.

**Submission information**: please submit on ZoneCours

- a PDF report
- your code

 
following the naming convention `PS4-studentid.extension` where `studentid` is replaced with your student ID and `extension` is the file extension (e.g., `.pdf`, `.R`, `.Rmd`, `.sps`)

**Instructions**: We consider data collected for Study 3 of @Grossman:2014 (click the links to download [the paper](https://journals.sagepub.com/stoken/default+domain/vIg5KBmaiJHKTXfUpXZK/full) and the [Supplementary material](https://journals.sagepub.com/doi/suppl/10.1177/0956797614535400/suppl_file/DS_10.11770956797614535400_SupplementalMethodandResults.pdf)). You can access these data directly from **R** from the `hecedsm` package or [download the SPSS data](/files/data/SPSS/GK14_S3.sav).


The purpose of the exercise is to reproduce part of Table S4 of the Supplementary material.
We will compute linear contrasts and adjust the resulting comparisons to account for multiple testing.^[Technical aside: there are four correlated outcome variables, so this is technically a multivariate problem. ]

We will fit one-way ANOVA model for each of the four response (`compr`,`limits`,`persp` and `change`) and for each age group separately. Thus, we will have four contrasts for each of the eight models (one per outcome and age group). The size of the family, assuming the global $F$-tests are not of interest, is thus $m=32$.

Use the [helper code](/evaluations/04-problem-set.R) to get started. Don't be intimidated: this task will involve a lot of copy-pasting. Fill the helper file code by replacing the `#TODO` statements and reach out for help if you are stuck.


1. Determine the contrast vectors (i.e., the weights) for the four hypothesis tests outlined in @Grossman:2014. 
2. Compute the contrasts in the pre-planned comparisons reported in Table S4. Check whether these match the reported values.^[The sign may be different from the paper depending on how you set up the contrasts, but the $p$-values should be the same.]
3. Using the helper code, obtain adjusted _p_-values using Bonferroni's method and compare them to (a) the raw _p_-values and (b) the Bonferroni-Holm adjusted _p_-values. How many of the planned comparisons are significant at level $\alpha=0.05$ if you modify the _p_-values?
4. Another way to present the results of the two-sided _t_-test for contrasts is to report confidence intervals rather than _p_-values. Which interval would be the largest between (a) an unadjusted confidence interval and (b) one derived using Bonferroni's method? Justify your answer.^[*Hint: Bonferroni's method amounts to making the tests at level $\alpha/m$. Try modifying the level in the code for the confidence intervals to see which is largest.*]

