---
title: "Problem set 9"
---

Complete this task in teams of two or three students.

**Submission information**: please submit on ZoneCours

-   a PDF report
-   your code


We consider Study 2 of @Bobak:2019, who collected responses for 52 participants and computed the average of the correctly identified figures as response out of 96 trials (32 per condition). @Bobak:2019 report that 

> Participants saw all 96 trials in a random order and the colour condition was counterbalanced for each set.


Perform a repeated measure one-way ANOVA with `color` as within-factor and `pcorr` as response with the `BMH19_S2` data, which can be found in the **R** package `hecedsm`.  You can also download the [SPSS database via this link](/files/data/SPSS/BMH19_S2.sav).

1. Explain in your own words the purpose of randomization and [counterbalancing](https://explorable.com/counterbalanced-measures-design) in a repeated measure experiment.
2. Is there evidence against the hypothesis of sphericity? Report Mauchly's statistic and the conclusion of the hypothesis test.
2. Are there differences overall between color match (monochrome, mixed or colored)? Report the $F$-statistic, the degrees of freedom and the $p$-value and a measure of effect size (e.g., $\widehat{R}^2_p$). If the sphericity assumption isn't met, use the Greenhouse--Geisser adjustment for the degrees of freedom of the tests and report the estimated correction factor $\widehat{\epsilon}$.
3. Compute pairwise differences applying Tukey's honest significance difference multiplicity correction. Report the pairwise differences in terms of percentage of correct values (differences in `pcorr`), the $t$-test statistics and the associated $p$-values.
4. An alternative procedure would be to fit the model as a one-way MANOVA: do this and report the value of Pillai's trace with the approximate $F$ statistic, degrees of freedom and $p$-values. Does your conclusions change?^[If you fit the model with `afex` package functions `aov_ez`, the output contains a slot `$Anova` with the value of this test.]
