---
title: "Problem set 11"
---

Complete this task in teams of up to three students.

**Submission information**: please submit on ZoneCours

-   a PDF report
-   your code

## Task 1

@Liu.Rim.Min.Min:2022 postulated in their Experiment 5b that the underestimation of the appreciation of initiators relative to recipients was mediated by the degree of surprise of the recipient. Their data can be obtained from `LRMM22_S5b`.

1. Fit the linear mediation model using the PROCESS macro or `mediate` function from the `mediation` package
  - use the nonparametric bootstrap with the percentile method
  - compare the coefficients with those of Figure 1 from the paper.
2. Identify the type of mediation (complementary, competitive or indirect only) based on coefficients.
3. The paper does not discuss any of the model assumptions.  List the assumptions of the linear mediation model and explain how some may fail to be valid, thus casting doubt on the conclusions drawn by @Liu.Rim.Min.Min:2022.


```{r}
#| eval: false
#| echo: false
data(LRMM22_S5b, package = "hecedsm")
model1 <- lm(surprise ~ condition,
                 data = LRMM22_S5b)
model2 <- lm(appreciation ~ surprise + condition,
             data = LRMM22_S5b)
linmedmod <- mediation::mediate(
  model.m = model1, 
   model.y = model2,
   boot.ci.type = "perc",
   boot = TRUE,
   mediator = "surprise",
   treat = "condition",
   treat.value = "other",
   control.value = "self",
   sims = 5000L)
```

## Task 2

Study 4 of @Risen/Gilovich:2008 (pp. 297-299) perform a mediation analysis with a two-way ANOVA using the @Baron/Kenny:1986 methodology. 

1. Read the description and comment on the following aspects:
    a. use of the Baron and Kenny original testing procedure^[The latter is said to be suboptimal; explain why in your words.]
    b. the plausibility of the causal model implied by the directed acyclic graph drawn in Figure 2.
2. Using the summary statistics and coefficients estimates reported, recompute Sobel's statistic^[Some authors may be excluding the $\mathsf{Va}(\widehat{\gamma})\mathsf{Va}(\widehat{\alpha})$ term from the equation.] and the _p_-value and compare them with the values reported.
.^[In **R**, the $p$-value for the two-sided test can be computed via `2*pnorm(abs(stat), lower.tail = FALSE)`, where `stat` is Sobel's statistic.]
3. List the assumptions of the linear causal mediation model. Are there any check of these and, if so, do they support the claims of the authors? 
3. Can the authors successfully claim mediation considering the study uses an experimental design and randomly allocates condition? Why or why not?
