---
title: "Critical review"
---


## Description of the task:

Select a scientific paper published in one of the journal in the list of the [Financial Times Top 50 list](https://www.ft.com/content/3405a512-5cbb-11e1-8f1f-00144feabdc0), on a preprint repository like [PsyArXiv](https://psyarxiv.com/), or in a top tier journal in your field of research **containing an experimental study**. Comment on the methodology, the statistical analyses and the report of the statistical results in the paper. The paper has to contain statistical analyses seen in class. If your selected paper has more than one study, you can select only one for the task.

You need to send a copy of your selected paper for approval **prior** to your peer review, which should be at most three pages long.

You should focus on the following elements in your review:

- Strengths and weaknesses of the methodology used to test the research hypotheses.
- Appropriateness of experimental design and the choice dependent variables, control variables, treatment
conditions.
- Appropriateness of statistical analyses.
- Presentation and discussion of the results (e.g., descriptive statistics, estimation of effect sizes, power calculations, etc.)
- Discussion of the limits of the study
- Possible sources of bias
- Pre-registration, reproducibility and transparency of the study. Assessment of the potential for replicability.

In addition to the material seen in class, see @Wilkinson:1999 and @Campion:1993 to inform your review. 

Note that many element of your review may be positive if the paper has already been published (especially in a top scientific journal, even if this is no guarantee of correctness).

## Deliverables

- A copy  of the article you are peer-reviewing
- A portable document file (PDF) of your critique (max 3 pages, excluding bibliography)

## Grading rubric

- Identification of strength and weaknesses: 10
- Correctness of the interpretation of statistical results: 10
- Scope: 10
- Clarity of report: 10
- Usefulness of suggestions: 5
- Writing and referencing: 5
