DATASET ACTIVATE DATABASE1. 
SORT CASES BY age. 
SPLIT FILE SEPARATE BY age. 


ONEWAY limits compr persp change BY condition
/CONTRAST=2 0 -1 -1
/CONTRAST=-1 1 0 0
/CONTRAST= 0 0 -1 1
/CONTRAST=0 2 -1 -1
/STATISTICS DESCRIPTIVES HOMOGENEITY
/MISSING ANALYSIS
/CRITERIA=CILEVEL(0.95).
