---
title: "Evaluations"
---


The main goals of this class are to help you understand the steps require to design and analyse the results of an experiment. 


## Weekly check-in

I want to hear back from you regarding the course material, activities and learning material. 



I will grade these check-ins using a check system:

- *110%*: Response shows phenomenal thought and engagement with the course content. I will not assign these often.
- *100%*: Response is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- *50%*: Response is hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I'm not grading your writing ability, I'm not counting the exact number of words you're writing, and I'm not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. I'm looking for thoughtful engagement, that's all. Do good work and you'll get a ✔.

You will submit these responses via ZoneCours. 


## Problem sets


There are 12 problem sets on the schedule. **I will keep the highest grades for 11 of them.** I will drop the lowest score - this means you can skip one of the problem sets. You need to show that you made a good faith effort to work each question. I will not grade these in detail. The problem sets will be graded using a check system:

- *110%*: Assignment is 100% completed. Every question was attempted and answered, and all answers are correct. Document is clean and easy to follow. Work is exceptional. I will not assign these often.
- *100%*: Assignment is complete.  Every question was attempted and answered, and most answers are correct. **This is the expected level of performance.**
- *75%*: Assignment is mostly complete and most answers are correct. 
- *50%*: Assignment is less than 50% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not assign these often.

You may (and should!) work together on the problem sets, but *you must turn in your own answers.* You cannot work in groups of more than **three** people, and you must note who participated in the group in your assignment.


## Final project

For your final project, you will perform a critical review of a peer-reviewed paper from a list containing an experiment and which uses one of the statistical techniques covered in class. You will pay particular attention to reproducibility, readability and the correctness of the analysis, discussing points of improvement, statistical fallacies. This will help you develop skills for efficient peer-review of the statistical methodology section.


## Final examination

There will be a closed-book final exam covering the content of the whole semester. Most of the questions will relate to the tasks you performed in problem set and to discussions we had in class. The exam will be in-person (see the Syllabus for details).


